version: '3.8'
volumes:
  car_data:
services:
  car-management-system:
    build: .
    image: car-management-system
    container_name: car-management-system
    stdin_open: true
    tty: true
    volumes:
      - car_data:/app/data