name: Release and Deploy

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: car-management-system

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image with Docker Compose
        run: docker compose build

      - name: Tag Docker Image
        run: docker tag ${{ env.IMAGE_NAME }} ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: |
            ## How to use this version
            
            ### Pull the image:
            ```bash
            docker pull ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ```

            ### Run the container:
            ```bash
            docker run -it --rm -v car_data:/app/data ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "username": "GitHub Actions",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "🚀 Nuova Release Pubblicata!",
                "description": "**${{ github.repository }}** ha rilasciato [${{ github.ref_name }}](${{ github.event.head_commit.url }})",
                "color": 3066993,
                "fields": [
                  {
                    "name": "Autore",
                    "value": "${{ github.actor }}",
                    "inline": true
                  },
                  {
                    "name": "Tag",
                    "value": "${{ github.ref_name }}",
                    "inline": true
                  }
                ]
              }]
            }' \
            $DISCORD_WEBHOOK_URL
